### PR TITLE
[fix] Only first page is displayed...

### PR DESCRIPTION
**Pull request by zamentur**
## Problem
https://github.com/YunoHost-Apps/libreto_ynh/issues/8

## Solution

Return to the old configuration

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by zamentur** [comment]
!testme

**Comment by ericgaspar** [comment]
When Libreto is installed in a Subdirectory, we lose the CSS styling. (The bug was already present in master)

**Comment by zamentur** [comment]
Yes in the past, this package was limited on root domain only. I am not sure the upstream is able to manage non root domain path ...

**Comment by zamentur** [comment]
But this fix the fact that it displayed 404 error on each libreto (root domain or not). Home page displayed but other pages are in 404.

**Pull request merged**
